### ISSUE TITLE
game-hud structure

### ISSUE THREAD

**Issue by AaronLayton** [jordanabram1997/PenguinPuncherApp#26]
The hud structure seems all wrong.

Re layout the hud with

```
.game-hud
    .game-hud__score
    .game-hud__stats
    .game-hud__progress-bar
````

**Comment by AaronLayton** [comment]
How we getting on with this JD?

**Comment by jordanabram1997** [comment]
Hello Aaron thanks for checking up on me yes I have completed many of the issues that I posted thank you for the help and the structure of my HTML looks much better :-)
