### ISSUE TITLE
Game not storing DATA

### ISSUE THREAD

**Issue by jordanabram1997** [jordanabram1997/PenguinPuncherApp#28]
When Playing the game if you refresh the page it doesn't store the data. This is needed as people need to carry on from were they left off

**Comment by AaronLayton** [comment]
Looks like you need to change the order around to this when calling `loadData()`

```javascript
settings = $.extend(defaultSettings, settings);
```

**Comment by jordanabram1997** [comment]
FIXED! thank you @AaronLayton
