### ISSUE TITLE
Progress Bar Level

### ISSUE THREAD

**Issue by jordanabram1997** [jordanabram1997/PenguinPuncherApp#32]
I need to have the progress bar in the middle of the bar at all times not the middle of the amount of xp you have. I have currently got the text inside the progress bar but only shows when you have started to click.

**Comment by jordanabram1997** [comment]
@AaronLayton @AndrewBeniston

**Comment by AaronLayton** [comment]
Just follow the Bootstrap example as it already works - if its not working on your version then you have done something wrong, try copy and pasting the example again

**Comment by jordanabram1997** [comment]
Okay thank you :)
