### ISSUE TITLE
Progress Bar Completion

### ISSUE THREAD

**Issue by jordanabram1997** [jordanabram1997/PenguinPuncherApp#7]
Progress Bar doesn't make it the full length when leveling up and on some levels doesn't even make half way !important!

**Comment by AaronLayton** [comment]
This was just a slight calculation error when we first figured it out

Change line 101 in game.js to the following
```javascript
var percentage = ( (settings.experience - experienceNeeded(settings.level)) / (experienceNeeded(settings.level + 1) - experienceNeeded(settings.level))) * 100;
```
